### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by xrevenge** [agungsugiarto/boilerplate#40]
On Lamp project, when i  folow install instruction, like that :

composer require agungsugiarto/boilerplate

Installation failed with this error message :
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - agungsugiarto/boilerplate 1.0.4 requires myth/auth dev-develop -> satisfiable by myth/auth[dev-develop] but these conflict with your requirements or minimum-stability.
    - agungsugiarto/boilerplate 1.0.3 requires myth/auth dev-develop -> satisfiable by myth/auth[dev-develop] but these conflict with your requirements or minimum-stability.
    - agungsugiarto/boilerplate 1.0.2 requires myth/auth dev-develop -> satisfiable by myth/auth[dev-develop] but these conflict with your requirements or minimum-stability.
    - agungsugiarto/boilerplate 1.0.1 requires myth/auth dev-develop -> satisfiable by myth/auth[dev-develop] but these conflict with your requirements or minimum-stability.
    - agungsugiarto/boilerplate 1.0.0 requires myth/auth dev-develop -> satisfiable by myth/auth[dev-develop] but these conflict with your requirements or minimum-stability.
    - Installation request for agungsugiarto/boilerplate ^1.0 -> satisfiable by agungsugiarto/boilerplate[1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4].

Installation failed, deleting ./composer.json.

**Comment by agungsugiarto** [comment]
Hello @xrevenge because packages myth/auth still on development, you need to change composer.json on root project. Add like this on your composer.json https://github.com/agungsugiarto/boilerplate/blob/master/composer.json#L27-L28

**Comment by xrevenge** [comment]
Thx for your response.

I add composer.json and then make composer install. 

Evrything was downloaded in the vendor directory.

Then , how can i install application ? I try to do php spark, but it doesn't work.

php spark auth:publish
Could not open input file: spark

**Comment by agungsugiarto** [comment]
Have you install ci 4 starter from this https://codeigniter4.github.io/userguide/installation/installing_composer.html ?

**Comment by xrevenge** [comment]
This My step now :

- Create composer.json like your
- Make codeigniter installation ( I had a problem with directory name "codeinginiter" vs "codeigniter4").
Everything is ok;

Then i follow  your instructions :

.env is ok
- Run php spark auth:publish
- Add instructions in Config

My problem is when i do that : php spark boilerplate:install

Response is there

ci4@srv02:~/demobis$ php spark boilerplate:install


CodeIgniter CLI Tool - Version 4.0.2 - Server-Time: 2020-04-01 02:29:20am

Command "boilerplate:install" not found.

**Comment by agungsugiarto** [comment]
I think you miss to directory try first:
```bash cd your-project```

**Comment by agungsugiarto** [comment]
This guide spesial for you!

1. go to path your project
```bash
composer create-project codeigniter4/appstarter project-root
```
2. Open directory project-root
```bash
cd project-root
```
3. Require boilerplate
```bash
composer require agungsugiarto/boilerplate
```
4. In directory project-root open composer.json and add code like [this](https://github.com/agungsugiarto/boilerplate/blob/master/composer.json#L27-L28) or below like this.
```bash
"minimum-stability": "dev",
 "prefer-stable": true,
```

5. You can next prosess installation to step 2 in readme.md
