### ISSUE TITLE
Error in configuration

### ISSUE THREAD

**Issue by cseoneohs** [agungsugiarto/boilerplate#57]
Hello,
Find a little error here :
    'emailForgot'     => 'agungsugiarto\boilerplate\Views\Authentication\emails\fogot',
need to be replace by :
    'emailForgot'     => 'agungsugiarto\boilerplate\Views\Authentication\emails\forgot',
Thank's for All !!

**Comment by agungsugiarto** [comment]
Thank you for remind, my bad typo on readme.md. If you have more issue please let me know.

**Comment by cseoneohs** [comment]
All is working fine, thank's !
