### ISSUE TITLE
bug in header.php 

### ISSUE THREAD

**Issue by jorgemartinsalas** [agungsugiarto/boilerplate#66]
Line number 48 of the Views/layout/header.php file should be replaced by:

`<a href="<?= route_to('logout') ?>" class="btn btn-primary btn-block"><b><?= lang('boilerplate.global.close') ?></b></a>`

you currently have an error in: `<b> Logout</b>`

in the same file line number 41 should be replaced by:
 ` <span><?= lang('boilerplate.user.fields.join') ?></span> `
you currently have an error in: `lang('user.join')`

**Comment by agungsugiarto** [comment]
The error are you mean, not translated, right ?

**Comment by agungsugiarto** [comment]
fixed
