### ISSUE TITLE
Manual Installation

### ISSUE THREAD

**Issue by InsiteFX** [agungsugiarto/boilerplate#67]
How to Manually install this without Composer, my server will not allow Composer.

**Comment by agungsugiarto** [comment]
Manually, by go to app/ThirdParty directory in project root, and clone this repository to the app/ThirdParty directory:

cd app/ThirdParty git clone git@github.com:agungsugiarto/boilerplate.git

see https://help.github.com/en/github/authenticating-to-github/error-permission-denied-publickey# for common clone issue troubleshooting.

then register "boilerplate" to App/Config/Autoload.php's psr4 property:

		$psr4 = [ 			'App' => APPPATH, // To ensure filters, etc still found, 			APP_NAMESPACE => APPPATH, // For custom namespace 			'Config' => APPPATH . 'Config', 			'Album' => APPPATH . 'ThirdParty/boilerplate/src', // <-- add this line 		];

**Comment by agungsugiarto** [comment]
You can install on local machine, then upload the whole project to your server.
