### ISSUE TITLE
Seeder bug.

### ISSUE THREAD

**Issue by InsiteFX** [agungsugiarto/boilerplate#68]
**Describe the bug**
Getting this error on the database seeder CodeIgniter 4 newest developer version today.

The specified Seeder is not a valid file: C:\xampp\htdocs\admin\app\Database/Seeds/db:seed.php

It creates the tables in the database but then throws that error above.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by agungsugiarto** [comment]
What command are you try?

**Comment by InsiteFX** [comment]
Ok, the problem is on your end your php spark boilerplate:install no longer works! I I did this in the home controller and it worked fine.

`$seeder = Database::seeder();
		$seeder->call('agungsugiarto\boilerplate\Database\Seeds\BoilerplateSeeder');`

**Comment by AbdulRafay** [comment]
@InsiteFX I have version 4.0.4 and still not able to run seeder, please refer to screenshot below:

![image](https://user-images.githubusercontent.com/614883/87855565-b0cd1700-c932-11ea-9a13-26b1594de5d6.png)

I get following error:

![image](https://user-images.githubusercontent.com/614883/87855587-cfcba900-c932-11ea-8cf6-eebc6f7977e8.png)

**Comment by InsiteFX** [comment]
Just do this in your controller index method.

`$seeder = Database::seeder();`
`$seeder->call('agungsugiarto\boilerplate\Database\Seeds\BoilerplateSeeder');`

And it should work for you, if you change the public folder you also need to set the new path in spark.

**Comment by AbdulRafay** [comment]
@InsiteFX thank you for  your kind help

i tried and got following error:
![image](https://user-images.githubusercontent.com/614883/87856633-c98cfb00-c939-11ea-861d-044a8e6659cb.png)

**Comment by AbdulRafay** [comment]
it seems like beside the exception, database is populated with seed values

**Comment by InsiteFX** [comment]
Added $arguments parameter to after() and before() in FilterInterface. This is a breaking change, so all code implementing the FilterInterface must be updated

**Comment by madtechservices** [comment]
I moved the file 'agungsugiarto\boilerplate\Database\Seeds\BoilerplateSeeder.php' to 'app\Database\Seeder'
Then I modified the BoilerplateSeeder.php file with the following (just the first 12 lines here, nothing else needed to be changed).

`<?php namespace App\Database\Seeds;

use CodeIgniter\Config\Services;
use CodeIgniter\Database\Seeder;
use Myth\Auth\Entities\User;
use Myth\Auth\Models\UserModel;

/**
 * Class BoilerplateSeeder.
 */
class BoilerplateSeeder extends \CodeIgniter\Database\Seeder
{`

Then run `php spark db:seed BoilerplateSeeder`

And all should work ok. :)

**Comment by InsiteFX** [comment]
They have also added a Database Seeder Generator now.

New command, make:seeder to generate a :doc:`Database Seed class </dbmgmt/seeds>` skeleton file.

**Comment by agungsugiarto** [comment]
@InsiteFX fixed for now using your code, thanks.

> 
> 
> Just do this in your controller index method.
> 
> `$seeder = Database::seeder();`
> `$seeder->call('agungsugiarto\boilerplate\Database\Seeds\BoilerplateSeeder');`
> 
> And it should work for you, if you change the public folder you also need to set the new path in spark.

Thanks @InsiteFX, fixed for now.
