### ISSUE TITLE
No such file or directory /vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php - 225

### ISSUE THREAD

**Issue by gosocial2** [agungsugiarto/boilerplate#69]
**No such file or directory**
`php spark boilerplate:install `
runs prematurely.

**To Reproduce**
1.  `composer create-project codeigniter4/appstarter agungsugiartoboilerplate`
2.  Follow STEP 1 of the instructions on https://github.com/agungsugiarto/boilerplate/blob/master/README.md
3. `composer require agungsugiarto/boilerplate`
4.  Follow the rest of instructions (from STEP 2 to STEP 4) on https://github.com/agungsugiarto/boilerplate/blob/master/README.md
5. php spark boilerplate:install

**Terminal Output with Errors**
```
go$ php spark boilerplate:install
CodeIgniter CLI Tool - Version 4.0.3 - Server-Time: 2020-07-15 03:37:09am

  created: Config/Boilerplate.php
  created: Database/Migrations/2020-02-03-081118_create_menu_table.php
Running all new migrations...

No such file or directory
/Applications/MAMP/htdocs/agungsugiartoboilerplate/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php - 225


No such file or directory
/Applications/MAMP/htdocs/agungsugiartoboilerplate/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php - 225
```

**Comment by agungsugiarto** [comment]
Hello, i think this because connection issue with your config. Can you verify this issue guys @InsiteFX, @AbdulRafay ?

**Comment by AbdulRafay** [comment]
I did not face this issue. I this it is because of missing database driver. 

@gosocial2  please try running the following command

sudo apt install php7.2-pdo php7.2-mysql

NOTE: please adjust the command as per your php version

**Comment by InsiteFX** [comment]
You may need to edit your php.ini file and make sure that the PDO extension is not remarked out ; semi-colon in front of it.

**Comment by gosocial2** [comment]
@AbdulRafay and @InsiteFX , thank you both for your replies.

PDO is already enabled in my php.ini, (I have other non-framework-based apps using it), but it is not enabled in my CI4/Boilerplate project's .env settings:

`database.default.DBDriver = MySQLi`

This migration issue occurred with some other CI4 projects I created, too, so I opened an issue there (https://github.com/codeigniter4/CodeIgniter4/issues/3359)

Are you guys saying that switching to PDO can be a workaround?

**Comment by InsiteFX** [comment]
I' am using the MySQLi driver and everything is running fine here, the only difference is that
I manually installed Boilerplate.

**Comment by gosocial2** [comment]
> I' am using the MySQLi driver and everything is running fine here, the only difference is that
> I manually installed Boilerplate. I know that Lonnie also updated the Myth/Auth a couple of days ago for the new filer parameters.

Can you briefly describe the manual installation step? Still require myth/auth via composer? And where to paste copied contents of Boilerplate/src/*.* ?

**Comment by InsiteFX** [comment]
I manually install Myth/Auth also.

**Comment by gosocial2** [comment]
In the .env file,  changing 

`database.default.hostname = localhost`

to

`database.default.hostname = 127.0.0.1`

solves the issue.

You might want to update the README.MD section for INSTALLATION step 2.

Thanks for your help anyway.
