### ISSUE TITLE
language bug

### ISSUE THREAD

**Issue by jorgemartinsalas** [agungsugiarto/boilerplate#72]
if I configure my application in the following way:
in app/Config/App.php
public $defaultLocale = 'ar';
public $negotiateLocale = false;
public $supportedLocales = ['ar'];
public $appTimezone = 'America/Argentina/Salta';
public $charset = 'UTF-8';

in app/Config/Boilerplate.php
 public $i18n = 'Spanish';

then I get this error. In my-app/admin/user/profile
Exception
DateTime::__construct(): Failed to parse time string (٢٠٢٠-٠٨-٠٣ ١٧:٠٠:٤٩) at position 0 (�): Unexpected character

https://subefotos.com/ver/?e87dadd2778911569dd6270b16cdedd1o.png

**Comment by agungsugiarto** [comment]
The function humanize() is extends from Time() class, i believe codeigniter 4 related bug. Please summit issue to https://github.com/codeigniter4/CodeIgniter4
