### ISSUE TITLE
Replace route_to() with base_url()

### ISSUE THREAD

**Issue by ixiDev** [agungsugiarto/boilerplate#73]
Hi. thanks for this awesome  code 😄 

After i install this library i got meany errors on datatable  like this ;

`DataTables warning: table id=table-user - Ajax error. For more information about this error, please see http://datatables.net/tn/7`

So i search for the problem and i found its come from ajax script when you want to fill the DataTable
 
here is your code if file Views/*/index.php

```
.....
 ajax : {
            url: '<?= route_to('admin/role') ?>',
            method: 'GET'
        },
.....
```
 I set app baseUrl in .env like this 

`app.baseURL = 'http://localhost/boilerplate/public/'`
and I am using Xampp 
the **route_to()** function  always returned the link like this **http://localhost/admin/role** but i want it like this **http://localhost/boilerplate/public/admin/role**

so i replace **route_to()** with **base_url()** and i solve the problem , is it safe to do this !
Thanks again ❤️

**Comment by agungsugiarto** [comment]
Hello @ixiDev pr are welcome for fix this issue.

**Comment by ixiDev** [comment]
> Hello @ixiDev pr are welcome for fix this issue.

Hi. I switched to Laragon and it's working perfectly : smile 
The issue comes from configuration of Xampp , you should put your baseUrl in  config of Xampp not in .env 
 Just close this :smile 

Thanks again :heart
