### ISSUE TITLE
Another DataTables error not changing language to English.

### ISSUE THREAD

**Issue by InsiteFX** [agungsugiarto/boilerplate#77]
New issue, Setting the boilerplate config i19n to English but the DataTables buttons on top and bottom paging are not changing still using you i18n Indonesian.

Go to admin users and you will see the problem.

**Comment by agungsugiarto** [comment]
@InsiteFX see on demo, just fine. You probably need clear the cache browser or try with ignonito mode.

**Comment by InsiteFX** [comment]
I did do a hard cache reset in chrome and it still is showing your lanuage.

**Comment by InsiteFX** [comment]
I figured it out, I was editing the boilerplate Config when there is also a Boilerplate Config in app/Config.

So you can close this, I would add that to the readme could be confusing later on.
