### ISSUE TITLE
mas, ada bug ketika klik tombol update menu

### ISSUE THREAD

**Issue by bastomiadi** [agungsugiarto/boilerplate#80]
![Screenshot_2021-02-08_17-30-08](https://user-images.githubusercontent.com/13336571/107207957-84462d00-6a33-11eb-8aa1-7879a0d3f35d.png)
![Screenshot_2021-02-08_17-30-16](https://user-images.githubusercontent.com/13336571/107207968-87d9b400-6a33-11eb-8418-534f1a1570b9.png)

saya pakai  dev-master, kemarin2 habis composer update dan nemuin ini.

**Comment by agungsugiarto** [comment]
Apakah di demo mengalami error yg sama ?

**Comment by bastomiadi** [comment]
Dlu demo juga lancar tp pas sblum ngelakuin composer update

**Comment by bastomiadi** [comment]
Akun juga kaget tiga ada error itu, sblumnya normal

**Comment by agungsugiarto** [comment]
Di demo tidak ada error yg dimaksud. Pastikan appstarter dan condeigniter di update ke terbaru.

**Comment by bastomiadi** [comment]
Sudah ketemu mas permasalahannya, dikarenakan tabel prefix. Kalau gak pake tabel prefix memang bisa. Jadi dia ga kebaca mas tabel nya. 

Saya biasanya kalau bikin tabel ada prefix didepan misal tbl_users
Berlaku untuk smua tabel juga pake prefix tbl_

Bug sih mnurut ki itu.

**Comment by bastomiadi** [comment]
Saya dah pake ci versi 4.1.1

**Comment by agungsugiarto** [comment]
Bukan karena bug, karena memang default migrationnya tidak disertakan prefix. Tapi coba ditambahkan prefix di config database sepertinya bisa langsung ke inject nanti querynya.

**Comment by bastomiadi** [comment]
Iya itu saya bikin prefix nya di .env kok lalu drop smua tabel dan php spark migrate lagi

**Comment by bastomiadi** [comment]
![16128049854388652114446757424442](https://user-images.githubusercontent.com/13336571/107257206-030b8c00-6a6d-11eb-9e78-b8d6f729ce3d.jpg)
Tanpa prefix

**Comment by bastomiadi** [comment]
![Uploading 16128051897244724022235679121943.jpg…]()
Pakai prefix tbl_

**Comment by bastomiadi** [comment]
![16128052561851589483310506969124](https://user-images.githubusercontent.com/13336571/107257783-a361b080-6a6d-11eb-97a9-561f55cb6fac.jpg)

**Comment by agungsugiarto** [comment]
coba lihat config .env

**Comment by bastomiadi** [comment]
![Screenshot_2021-02-09_00-45-48](https://user-images.githubusercontent.com/13336571/107259931-2dab1400-6a70-11eb-8ccb-56daaf055590.png)

**Comment by bastomiadi** [comment]
![Screenshot_2021-02-09_00-49-52](https://user-images.githubusercontent.com/13336571/107260488-bde95900-6a70-11eb-81f3-66bf02b6e127.png)
tanpa prefix

**Comment by agungsugiarto** [comment]
apakah tabel yg lain tidak bermasalah? hanya table group menu yg error ?

**Comment by bastomiadi** [comment]
Iya tidak masalah kalau yg lainnya. Tp untuk hapus data menu, tambah bisa kok

**Comment by agungsugiarto** [comment]
Iya dibuat pengecualian saja, table menu tidak perlu dibuat prefix. Kemungkinan karena ada query yg tidak tercover sama query builder, di menu model ada query group_concat untuk mysql dan postgre.

**Comment by bastomiadi** [comment]
Sementara gak pake prefix dlu mas, eh iya ini udh support validation image mas? Soalnya aku coba kok error terus padahal dah terisi file input nya.

**Comment by bastomiadi** [comment]
Dia gak bisa baca request->getFile()

**Comment by bastomiadi** [comment]
![Screenshot_2021-02-09_15-26-28](https://user-images.githubusercontent.com/13336571/107336047-43a9ea80-6aeb-11eb-8585-68007fc41b22.png)

**Comment by agungsugiarto** [comment]
Coba dibaca lagi dokumentasi ci4, gak ada hubungan boilerplate sama error gak bisa upload image. Kalau issue ini sudah clear bisa di close.

**Comment by bastomiadi** [comment]
Siap mas, makasih sbelumnya.. Library nga bagus mas dan ini library pertama saya pake di ci4 hehe. Oke karena dah solved. Saya tutup aja ya..
