### ISSUE TITLE
how to move all the views file to default app\views folder

### ISSUE THREAD

**Issue by truelineinfotech** [agungsugiarto/boilerplate#81]
**Is there any feature to move all views files (including theme files, layout etc..) to App\views folder**
`agungsugiarto\boilerplate\Views` to `App\views`

or how to modify dashboard view file without touching `agungsugiarto\boilerplate\src` folder

**Comment by agungsugiarto** [comment]
Unfortunately this is not be move to app
 folder, if you want interact with view components, you must call with full path namespace.

Example: https://github.com/agungsugiarto/boilerplate/blob/090fe5885bf408a287ec9bb6783d566a24a46b19/src/Views/dashboard.php#L2

Reference: https://codeigniter4.github.io/userguide/outgoing/views.html#namespaced-views

**Comment by truelineinfotech** [comment]
Ok. Thanks
