### ISSUE TITLE
Docker version

### ISSUE THREAD

**Issue by cod3rshotout** [agungsugiarto/boilerplate#82]
Hi, thanks for your amazing code, could you please create a docker-compose file to dockerize your boilerplate?

Thanks

**Comment by agungsugiarto** [comment]
Hello @cod3rshotout, thank u for suggestion. But for now i am not making docker image for package boilerplate. You are free to making your self docker image from repository demo, this repository already setup and with last version ci4 https://github.com/agungsugiarto/boilerplate-codeigniter4
