### ISSUE TITLE
Upload image pada mode edit

### ISSUE THREAD

**Issue by nimcomarketing** [agungsugiarto/boilerplate#84]
Halo mas,
saya sudah pake repo ini dan bagus mas. Yang jadi masalah adalah ketika saya membuat form untuk update kemudian menyertakan upload file/gambar maka validasinya selalu invalid. Klo mode create tidak ada masalah. Solusinya bagaimana ya?

**Comment by agungsugiarto** [comment]
Halo mas @nimcomarketing, error tersebut tidak ada hubungannya dengan package boilerplate ini. Silahkan mencari bantuan di group facebook / forum lalu sertakan juga potongan code lewat pastebin dan sertakan juga log errornya. Terima kasih, isssue ini saya tutup.
