### ISSUE TITLE
strong_password is not a valid rule

### ISSUE THREAD

**Issue by cod3rshotout** [agungsugiarto/boilerplate#86]
when I try to create a new user, I get this CodeIgniter Exception:

    CodeIgniter\Validation\Exceptions\ValidationException
    strong_password is not a valid rule.

guess the problem is related to UserController -> create()

**Comment by agungsugiarto** [comment]
This not related with this package, you need first read documentation myth-auth.

**Comment by DeHekOnline** [comment]
Sorry.. started checking it out myself. When added it is valid and a nice option to have.
