### ISSUE TITLE
Issue with myth/auth latest version

### ISSUE THREAD

**Issue by chrisastley** [agungsugiarto/boilerplate#91]
Hi, I've recently updated composer dependencies and had an issue when myth/auth updated to a new (non-beta) version which boilerplate doesn't like to work with. I've had to temporarily fix my composer version "myth/auth": "1.0-beta.3"

**Comment by agungsugiarto** [comment]
Hello @chrisastley, can you make pr to switch myth/auth requirement to stable release ? Thank u.

**Comment by chrisastley** [comment]
#92 Done. Thank you.

**Comment by chrisastley** [comment]
> Hello @chrisastley, can you make pr to switch myth/auth requirement to stable release ? Thank u.

Any chance you can have a look at the pull request and the issue mentioned above @agungsugiarto ?

**Comment by agungsugiarto** [comment]
Thank u @chrisastley, already merged.

**Comment by chrisastley** [comment]
Did you test that authentication still works ok on your boilerplate/theme? The issue I had was that the admin user didn't seem to have permission on some custom pages although I think they where added correctly to the menu builder and routes file.
