### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by mtaupiq** [agungsugiarto/boilerplate#93]
Mas ada typo nih https://github.com/agungsugiarto/boilerplate/blob/64908780261ed4bdc349fa923e8fc72ced96e741/src/Controllers/Users/UserController.php#L160

**Comment by mtaupiq** [comment]
![image](https://user-images.githubusercontent.com/9148854/125936186-00b84d57-c3b8-47c2-9fee-d8be7fc50a6b.png)
![image](https://user-images.githubusercontent.com/9148854/125936249-5d0f284c-fc85-4021-9a9d-46911b0c2571.png)

Mas ini salah nya dimana ya?

**Comment by agungsugiarto** [comment]
Load helper menu
